config/routes.rb
DouNiWan::Application.routes.draw do

  

  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/users/key_email/:email', to: 'users#key_email',via:'get'
  match '/users/add_friend/:id', to: 'users#add_friend',via:'get'
  resources :users do
	post 'add_group', :on => :collection
  end

end

app/models/firend.rb
class Firend < ActiveRecord::Base
  # 关系
  belongs_to :group
  belongs_to :user,:class_name => "User", :foreign_key => "user_id",:primary_key =>"id"
  belongs_to :own,:class_name => "User", :foreign_key => "own_id",:primary_key =>"id"

  scope :select_own, ->(id){where("own_id = ?",id)}
  scope :select_own_group, ->(id,g_id){where("own_id = #{id} and group_id = #{g_id}")}
  scope :exist_one, ->(user_id,own_id){where("own_id = #{own_id} and user_id = #{user_id}")}
end

app/models/group.rb
class Group < ActiveRecord::Base
  # 关系
  belongs_to :user
  
  scope :select_own, ->(id){where("user_id = ? ",id)}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # 头像上传
  mount_uploader :avatar, AvatarUploader
  
  # 密码加密
  has_secure_password

  # 关系
  has_many :groups
  has_many :firends,:class_name => "Firend", :foreign_key => "user_id",:primary_key =>"id"
  has_many :firends,:class_name => "Firend", :foreign_key => "own_id",:primary_key =>"id"

  # scope :select_email, -> (key){where("email like '#{key}%'")}

  # 得到身份
  def get_level
  	array=["齐天大圣","猴钻风","逗儿"]
  	array[self.level]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  helper_method :logined?, :current_user

  def current_user
    @current_user ||= login_from_session unless defined?(@current_user)
    @current_user
  end

  def sign_in(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logined?
    !current_user.nil?
  end

  def login_from_session
    if session[:user_id].present?
      begin
        User.find session[:user_id]
      rescue
        session[:user_id] = nil
      end
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
 	
  end

  def create
	  user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "欢迎你！#{user.name}"
      redirect_to users_path
    else
      flash[:danger] = "用户名或密码不一致，请确认重新登录！"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=current_user
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(get_user_params)
  	if @user.save
  	  sign_in @user
      flash[:success] = "欢迎你！#{@user.name}"
      redirect_to users_path
  	else
      flash[:danger] = "注册失败，请重新注册！"
  	  render 'new'
  	end
  end

  def add_group
    group = Group.new(name:params[:name],user_id:current_user.id)
    if group.save
      flash[:success] = "添加逗群成功！"
      redirect_to :back
    else
      flash[:danger] = "添加逗群失败！"
      redirect_to :back
    end
  end

  def add_friend
    firend = Firend.new(user_id:params[:id],own_id:current_user.id)
    if firend.save
      flash[:success] = "添加逗友成功！"
      render 'index'
    else
      flash[:danger] = "添加逗友失败！"
      render 'index'
    end
  end

  def key_email
    key=params[:email].gsub("~",".")
    user = User.find_by_email(key)
    # logger.info "--------#{current_user.id}-------------#{user.id}------------------------"
    if Firend.exist_one(user.id,current_user.id).blank?
      render :json => user.to_json
    else
      render :json => "".to_json
    end
  end

  private
    def get_user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation,:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_bottom.html.erb
<div id="page_bottom">
  <p>copyright @逗你玩开发人员自己玩</p>
</div>

app/views/layouts/_header.html.erb
<div id="page_header">
  <div class="content">
  	<div id="logo_image">
  	  <%=image_tag("logo.png") %>
  	</div>
  	<div id="logo_ul">
	  <ul>
      <% if logined? %>
        <li><%= link_to current_user.name,user_path(current_user)%></li>
        <li><%= link_to "退出",session_path(current_user),method: "delete",data:{ confirm: '确认退出吗?' } %></li>
      <% else %>
        <li><%= link_to "登录",new_session_path %></li>
        <li><%= link_to "注册",new_user_path %></li>
      <% end %>
	  	<li><a href="#">关于</a></li>
	  </ul>
  	</div>
  	<div class="clr"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>逗你玩</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= render 'layouts/header'%>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div>
  <%= yield %>
</div>


<%= render 'layouts/bottom'%>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_firends.html.erb
<div id="firends_list">
  <div id="user_header">
  	<div id="user_avater">
  	  <%= link_to("#",:target => "_blank") do %>
        <%= image_tag("default_avatar.jpg",class: "img-circle") if !current_user.avatar?%>
        <%= image_tag(current_user.avatar_url(:min_avatar),class: "img-circle") if current_user.avatar?%>
      <% end %>
  	</div>
  	<div id="user_intro">
  	  <ul>
  	  	<li>
          <%= link_to("#",:target => "_blank") do %>
            <span class="glyphicon glyphicon-user">：<%= current_user.name%></span>
          <% end %>
        </li>
  	  	<li id="user_identy">
          <%= link_to("#",:target => "_blank") do %>
            <span class="glyphicon glyphicon-star-empty">：<%= current_user.get_level%></span>
          <% end %>
        </li>
  	  </ul>
  	</div>
  	<div class="clr"></div>
  </div>
  
  <div id="user_body">
    <div class="sidebar">
      <ul class="nav" role="complementary">

        <li class="group_list">
          <h5>所有逗友<span class="caret"></span></h5>
          <ul class="nav">
            <% Firend.select_own(current_user.id).each do |i| %>
              <li class="firend_name_list">
                <%= link_to("#") do %>
                  <%= image_tag("default_avatar.jpg",class: "img-rounded firend_avatar") if !i.user.avatar?%>
                  <%= image_tag(i.user.avatar_url(:min_avatar),class: "img-rounded firend_avatar") if i.user.avatar?%>
                  <%= i.user.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>

        <% Group.select_own(current_user.id).each do |r|%>
          <li class="group_list">
            <h5><%=r.name %><span class="caret"></span></h5>
            <ul class="nav">
            <% Firend.select_own_group(current_user.id,r.id).each do |i| %>
              <li class="firend_name_list">
                <%= link_to("#") do %>
                  <%= image_tag("default_avatar.jpg",class: "img-rounded firend_avatar") if !i.user.avatar?%>
                  <%= image_tag(i.user.avatar_url(:min_avatar),class: "img-rounded firend_avatar") if i.user.avatar?%>
                  <%= i.user.name %>
                <% end %>
              </li>
            <% end %>
            </ul>
          </li>
        <% end %>


      </ul>
    </div>
  </div>

  <div id="user_bottom">
  	<div id="user_function_edit">
  	  <button type="button" class="user_function_button">
        <span class="glyphicon glyphicon-cog"></span>
      </button>
  	</div>
  	<div id="user_function_add">
  	  <button type="button" class="user_function_button" id="user_add_button">
        <span class="glyphicon glyphicon-plus"></span>
      </button>
  	</div>
  </div>
</div>

<%= render 'shared/user_add'%>

app/views/shared/_user_add.html.erb
<div class="modal fade request_modal" id="user_add_modal" tabindex="-1" role="dialog" aria-labelledby="contactLabel" aria-hidden="false" data-backdrop="static">
  <div class="modal-dialog">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <button type="button" class="close user_add_modal_close">×</button>
        <h4 class="panel-title" id="contactLabel">逗＋逗</h4>
      </div>

      <div class="modal-body">

        <ul class="nav nav-tabs" role="tablist">
          <li class="active"><a href="#add_group" role="tab" data-toggle="tab">＋逗群</a></li>
          <li><a href="#add_user" role="tab" data-toggle="tab">＋逗友</a></li>
        </ul>
        
        <div class="tab-content" style="margin: 10px; min-height: 150px;">

          <div class="tab-pane fade active in" id="add_group">
            <%= form_tag(add_group_users_path,method:'post') do %>
              <div class="form-group">
                <%= label_tag '逗群名' %>
                <%= text_field_tag 'name',nil,:class => "form-control"%>
              </div>
              <div class="form-group">
                <%= submit_tag '添加', class: "btn btn-large btn-success" %>
              </div>
            <% end %>
          </div>

          <div class="tab-pane fade" id="add_user">
            <div class="form-group">
              <%= label_tag '逗友邮箱' %>
              <%= text_field_tag 'email',nil,:class => "form-control user_add_firend",placeholder:"邮箱，一定要正确哦！"%>
            </div>
            <div class="form-group">
              <label style="display: block;border-bottom: 1px solid gray;">查询结果</label>
              <div class="key_result">
                <div class="key_result_itme key_result_avatar">
                </div>
                <div class="key_result_itme key_result_name">
                </div>
                <div class="key_result_itme key_result_link">
                </div>
                <div class="clr"></div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id="container">
  <%= render 'shared/firends'%>
  <div id="msg_content"></div>
</div>

app/views/users/new.html.erb
<div id="signin_box">
  <%= render 'shared/error_messages' %>
  
  <%= form_for(@user) do |f| %>

    <div class="form-group">
      <%= f.label :用户头像 %>
      <%= f.file_field :avatar,:class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :用户名 %>
      <%= f.text_field :name,:class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :邮箱 %>
      <%= f.text_field :email,:class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :密码 %>
      <%= f.password_field :password,:class => "form-control" %>	
    </div>

    <div class="form-group">
      <%= f.label :密码确认 %>
      <%= f.password_field :password_confirmation,:class => "form-control" %>  
    </div>

    <div class="form-group">
      <%= f.submit "注册", class: "btn btn-large btn-success",:id => "signin_submit"%>
    </div>
    <div class="clr"></div>
  <% end %>
</div>